version: '3'

networks:
    db_network:
    final_db_network:

volumes:
    final_db:

services:
    db:
        container_name: postgres_1
        image: postgres:12
        restart: always
        env_file:
            - ./.db.env
        volumes:
            - ./dbdata:/var/lib/postgresql/data
            - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
        networks:
            - db_network

    final_db:
        container_name: postgres_2
        image: postgres:12
        restart: always
        env_file:
            - ./.db.env
        volumes:
            - ./final_dbdata:/var/lib/postgresql/data
            - ./final_db/northwind_final_db.sql:/docker-entrypoint-initdb.d/init.sql
            - ./final_db/drop_constraints.sql:/scripts/drop_constraints.sql
            - ./final_db/add_constraints.sql:/scripts/add_constraints.sql
        networks:
            - final_db_network

    db_worker:
        container_name: db_worker_1
        image: python:3.9
        volumes:
            - ./data/postgres:/data
            - ./db_worker:/db_worker
        working_dir: /db_worker
        env_file:
            - ./.db.env
            - ./.env
        command: bash ./db_worker.sh
        networks:
            - db_network
        depends_on:
            - db

    csv_worker:
        container_name: csv_worker_1
        image: python:3.9
        volumes:
            - ./data/csv:/data
            - ./data/order_details.csv:/csv_worker/order_details.csv
            - ./csv_worker:/csv_worker
        working_dir: /csv_worker
        env_file:
            - ./.env
        command: bash ./csv_worker.sh

    final_db_worker:
        container_name: final_db_worker_1
        image: python:3.9
        volumes:
            - ./extracted_data:/extracted_data
            - ./data/postgres:/data
            - ./data/csv:/data/order_details
            - ./final_db_worker:/final_db_worker
        working_dir: /final_db_worker
        env_file:
            - ./.db.env
            - ./.env
        command: bash ./final_db_worker.sh
        networks:
            - final_db_network
        depends_on:
            - final_db

